syntax = "proto3";

package auth;

// Настройки для генерации Go кода.
option go_package = "github.com/iskanye/utilities-payment-proto/auth";

service Auth {
  rpc Register (RegisterRequest) returns (RegisterResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc IsAdmin (User) returns (Permissions);
}

message RegisterRequest {
  string email = 1; 
  string password = 2; 
}

message RegisterResponse {
  int64 user_id = 1; 
}

message LoginRequest {
  string email = 1; 
  string password = 2;
}

message LoginResponse {
  string token = 1;
}

message User {
  int64 user_id = 1;
}

message Permissions {
  bool isAdmin = 1;
}