// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillId        *int64                 `protobuf:"varint,1,opt,name=bill_id,json=billId,proto3,oneof" json:"bill_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DueDate       *string                `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bill) Reset() {
	*x = Bill{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetBillId() int64 {
	if x != nil && x.BillId != nil {
		return *x.BillId
	}
	return 0
}

func (x *Bill) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Bill) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bill) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Bill) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

type BillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillId        int64                  `protobuf:"varint,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillResponse) Reset() {
	*x = BillResponse{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillResponse) ProtoMessage() {}

func (x *BillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillResponse.ProtoReflect.Descriptor instead.
func (*BillResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *BillResponse) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

type BillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillId        int64                  `protobuf:"varint,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillRequest) Reset() {
	*x = BillRequest{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillRequest) ProtoMessage() {}

func (x *BillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillRequest.ProtoReflect.Descriptor instead.
func (*BillRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *BillRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

type BillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillsRequest) Reset() {
	*x = BillsRequest{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillsRequest) ProtoMessage() {}

func (x *BillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillsRequest.ProtoReflect.Descriptor instead.
func (*BillsRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

func (x *BillsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillId        int64                  `protobuf:"varint,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{4}
}

func (x *PayRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

type PayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResponse) Reset() {
	*x = PayResponse{}
	mi := &file_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResponse) ProtoMessage() {}

func (x *PayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResponse.ProtoReflect.Descriptor instead.
func (*PayResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{5}
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\abilling\"\xa8\x01\n" +
	"\x04Bill\x12\x1c\n" +
	"\abill_id\x18\x01 \x01(\x03H\x00R\x06billId\x88\x01\x01\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1e\n" +
	"\bdue_date\x18\x05 \x01(\tH\x01R\adueDate\x88\x01\x01B\n" +
	"\n" +
	"\b_bill_idB\v\n" +
	"\t_due_date\"'\n" +
	"\fBillResponse\x12\x17\n" +
	"\abill_id\x18\x01 \x01(\x03R\x06billId\"&\n" +
	"\vBillRequest\x12\x17\n" +
	"\abill_id\x18\x01 \x01(\x03R\x06billId\"'\n" +
	"\fBillsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"%\n" +
	"\n" +
	"PayRequest\x12\x17\n" +
	"\abill_id\x18\x01 \x01(\x03R\x06billId\"\r\n" +
	"\vPayResponse2\xd4\x01\n" +
	"\aBilling\x12/\n" +
	"\aAddBill\x12\r.billing.Bill\x1a\x15.billing.BillResponse\x122\n" +
	"\bGetBills\x12\x15.billing.BillsRequest\x1a\r.billing.Bill0\x01\x12.\n" +
	"\aGetBill\x12\x14.billing.BillRequest\x1a\r.billing.Bill\x124\n" +
	"\aPayBill\x12\x13.billing.PayRequest\x1a\x14.billing.PayResponseB4Z2github.com/iskanye/utilities-payment-proto/billingb\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_billing_proto_goTypes = []any{
	(*Bill)(nil),         // 0: billing.Bill
	(*BillResponse)(nil), // 1: billing.BillResponse
	(*BillRequest)(nil),  // 2: billing.BillRequest
	(*BillsRequest)(nil), // 3: billing.BillsRequest
	(*PayRequest)(nil),   // 4: billing.PayRequest
	(*PayResponse)(nil),  // 5: billing.PayResponse
}
var file_billing_proto_depIdxs = []int32{
	0, // 0: billing.Billing.AddBill:input_type -> billing.Bill
	3, // 1: billing.Billing.GetBills:input_type -> billing.BillsRequest
	2, // 2: billing.Billing.GetBill:input_type -> billing.BillRequest
	4, // 3: billing.Billing.PayBill:input_type -> billing.PayRequest
	1, // 4: billing.Billing.AddBill:output_type -> billing.BillResponse
	0, // 5: billing.Billing.GetBills:output_type -> billing.Bill
	0, // 6: billing.Billing.GetBill:output_type -> billing.Bill
	5, // 7: billing.Billing.PayBill:output_type -> billing.PayResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	file_billing_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}
