// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: billing.proto

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Billing_AddBill_FullMethodName  = "/billing.Billing/AddBill"
	Billing_GetBills_FullMethodName = "/billing.Billing/GetBills"
	Billing_GetBill_FullMethodName  = "/billing.Billing/GetBill"
	Billing_PayBill_FullMethodName  = "/billing.Billing/PayBill"
)

// BillingClient is the client API for Billing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingClient interface {
	AddBill(ctx context.Context, in *Bill, opts ...grpc.CallOption) (*BillResponse, error)
	GetBills(ctx context.Context, in *BillsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bill], error)
	GetBill(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*Bill, error)
	PayBill(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*PayResponse, error)
}

type billingClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient {
	return &billingClient{cc}
}

func (c *billingClient) AddBill(ctx context.Context, in *Bill, opts ...grpc.CallOption) (*BillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillResponse)
	err := c.cc.Invoke(ctx, Billing_AddBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) GetBills(ctx context.Context, in *BillsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bill], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Billing_ServiceDesc.Streams[0], Billing_GetBills_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BillsRequest, Bill]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Billing_GetBillsClient = grpc.ServerStreamingClient[Bill]

func (c *billingClient) GetBill(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*Bill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bill)
	err := c.cc.Invoke(ctx, Billing_GetBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) PayBill(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*PayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayResponse)
	err := c.cc.Invoke(ctx, Billing_PayBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServer is the server API for Billing service.
// All implementations must embed UnimplementedBillingServer
// for forward compatibility.
type BillingServer interface {
	AddBill(context.Context, *Bill) (*BillResponse, error)
	GetBills(*BillsRequest, grpc.ServerStreamingServer[Bill]) error
	GetBill(context.Context, *BillRequest) (*Bill, error)
	PayBill(context.Context, *PayRequest) (*PayResponse, error)
	mustEmbedUnimplementedBillingServer()
}

// UnimplementedBillingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServer struct{}

func (UnimplementedBillingServer) AddBill(context.Context, *Bill) (*BillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBill not implemented")
}
func (UnimplementedBillingServer) GetBills(*BillsRequest, grpc.ServerStreamingServer[Bill]) error {
	return status.Errorf(codes.Unimplemented, "method GetBills not implemented")
}
func (UnimplementedBillingServer) GetBill(context.Context, *BillRequest) (*Bill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBill not implemented")
}
func (UnimplementedBillingServer) PayBill(context.Context, *PayRequest) (*PayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayBill not implemented")
}
func (UnimplementedBillingServer) mustEmbedUnimplementedBillingServer() {}
func (UnimplementedBillingServer) testEmbeddedByValue()                 {}

// UnsafeBillingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServer will
// result in compilation errors.
type UnsafeBillingServer interface {
	mustEmbedUnimplementedBillingServer()
}

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) {
	// If the following call pancis, it indicates UnimplementedBillingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Billing_ServiceDesc, srv)
}

func _Billing_AddBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bill)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).AddBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_AddBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).AddBill(ctx, req.(*Bill))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_GetBills_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BillsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BillingServer).GetBills(m, &grpc.GenericServerStream[BillsRequest, Bill]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Billing_GetBillsServer = grpc.ServerStreamingServer[Bill]

func _Billing_GetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).GetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_GetBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).GetBill(ctx, req.(*BillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_PayBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).PayBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_PayBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).PayBill(ctx, req.(*PayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Billing_ServiceDesc is the grpc.ServiceDesc for Billing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Billing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Billing",
	HandlerType: (*BillingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBill",
			Handler:    _Billing_AddBill_Handler,
		},
		{
			MethodName: "GetBill",
			Handler:    _Billing_GetBill_Handler,
		},
		{
			MethodName: "PayBill",
			Handler:    _Billing_PayBill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBills",
			Handler:       _Billing_GetBills_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "billing.proto",
}
